# Configuration globale des runners GitHub
runners_defaults:
  base_image: ghcr.io/actions/actions-runner:2.328.0  # Image de base commune
  org_url: https://github.com/it-room
  # Le token GitHub doit être défini dans la variable d'environnement GITHUB_TOKEN (voir .env)

runners:
  - id: php83
    name_prefix: itroom-runner-php83
    labels: [itroom-runner-set-php83, php8.3]
    nb: 2
    build_image: ./config/Dockerfile.php83
    techno: php
    techno_version: 8.3
  - id: node20
    name_prefix: itroom-runner-node20
    labels: [itroom-runner-set-node20, node20]
    nb: 0
    build_image: ./config/Dockerfile.node20
    techno: node
    techno_version: 20
